/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emergencias_medicas.ui;

import java.util.Calendar;

/**
 *
 * @author Ruben
 */
public class EstablecerPago extends javax.swing.JInternalFrame {

    /**
     * Creates new form EstablecerPago
     */
    public EstablecerPago() {
        initComponents();
                                                    
//        Integer dia= Integer.decode(this.txtDia.getText());
//        Integer mes= Integer.decode(this.txtMes.getText());
//        Integer año= Integer.decode(this.txtAño.getText());
//        
//        this.afiliado.setNombre(this.jTextField1.getText()); 
//        
//        if(dia>31){
//            JOptionPane.showMessageDialog(rootPane, "Error en el numero ingresado");
//        }    
//        else if ((dia>30&&(mes==4||mes==6||mes==9||mes==11))||(dia>28&&mes==2)){
//            JOptionPane.showMessageDialog(rootPane, "Error en el numero ingresado");
//        }
//        else{
            //Calendar cal = Calendar.getInstance();
        
            //DateFormat formato= new SimpleDateFormat("yyyy-MM-dd");
        
            //String fecha = formato.format(cal.getTime());
        
//            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        
//
//        try{
//            Date fechaPago= dateFormat.parse(this.txtAño.getText()+"-"+this.txtMes.getText()+"_"+this.txtDia.getText());
//            this.afiliado.setFechaUltPago(fechaPago);
//            
//            
//        }catch(ParseException e){
//            JOptionPane.showMessageDialog(rootPane, "Fecha no establecida");
//        };
        

        this.afiliado.setNombre(this.jTextField1.getText());
        Calendar cal = Calendar.getInstance();
        this.afiliado.setCal(cal);
        this.dispose();
        
//        DateFormat formato= new SimpleDateFormat("yyyy-MM-dd");
//        
//        String fecha = formato.format(cal.getTime());
//        
//        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        
//        System.out.println("Dia elegido :" + cal.get(Calendar.DAY_OF_MONTH));
        
        
            
//        }
        
    
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
