
package emergencias_medicas.ui;

import emergencias_medicas.Afiliado;
import emergencias_medicas.Gestor;
import emergencias_medicas.Pago;
import emergencias_medicas.Persona;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;


public class ListaPagos extends javax.swing.JDialog {
    
    private DefaultListModel listModel = new DefaultListModel();
    //JTextField jTextField1;
    
    /**
     * Creates new form ListaPagos
     */
    public ListaPagos(java.awt.Frame parent, boolean modal, String docu, Gestor gestor) {
        super(parent, modal);
        initComponents();
        Calendar cal = Calendar.getInstance();
        Integer año= cal.get(Calendar.YEAR);
        //Integer mes= cal.get(Calendar.MONTH);
        
        
        for (int i = 0; i < gestor.getPersonas().size(); i++){
            Persona persona=(Persona) gestor.getPersonas().get(i);//obtiene todos los elementos del arraylist, uno x uno
            if(persona instanceof Afiliado && persona.getDni().equals (docu)){   //si pertence a la clase Afiliado
                Afiliado afi= (Afiliado) gestor.getPersonas().get(i);
                int tam= afi.getPagos().size()-1;
                int mesAlta= afi.getFechaAlta().get(Calendar.MONTH);
                
                if(año==afi.getFechaAlta().get(Calendar.YEAR)){
                    int difMeses= cal.get(Calendar.MONTH)-mesAlta;
                    this.jLabel2.setText("Adeuda "+(difMeses-tam)+" mes(es)");

                }else{                              //si es distinto el año
                    int calculoMeses= 11-mesAlta;
                    int difMeses=calculoMeses+cal.get(Calendar.MONTH)+1;
                    this.jLabel2.setText("Adeuda "+(difMeses-tam)+" mes(es)");
                }
               
                this.jLabel1.setText("Pagos de "+afi.getNombre()+" "+afi.getApellido()+
                    "      Afiliado el "+afi.toStringFecha());
                
                for(int j = 0; j< afi.getPagos().size(); j++){
                    Pago pago= afi.getPagos().get(j);
                    listModel.addElement(pago); //lo incluye en la lista
                }
            }
        }
        jList1.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(186, 186, 186)
                            .addComponent(btnAceptar))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<Pago> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
