/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emergencias_medicas.ui;

import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import emergencias_medicas.Movil;
import emergencias_medicas.Gestor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;

/**
 *
 * @author Carlos Mansilla
 */
public class UIPrincipal extends javax.swing.JFrame {
    
    private Gestor gestor;

    /**
     * Creates new form UI_Principal
     */
    public UIPrincipal(Gestor gestor) {
        this.gestor=gestor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        altaAfiliado = new javax.swing.JMenuItem();
        altaFamilia = new javax.swing.JMenuItem();
        altaMovil = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        bajaMovil = new javax.swing.JMenuItem();
        Pago = new javax.swing.JMenuItem();
        mItmAltaSolicitud = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        listaMoviles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        jMenu1.setText("Administraccion");

        jMenu4.setText("Alta");

        altaAfiliado.setText("Afiliado");
        altaAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaAfiliadoActionPerformed(evt);
            }
        });
        jMenu4.add(altaAfiliado);

        altaFamilia.setText("Familia de Afiliados");
        altaFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaFamiliaActionPerformed(evt);
            }
        });
        jMenu4.add(altaFamilia);

        altaMovil.setText("Movil");
        altaMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaMovilActionPerformed(evt);
            }
        });
        jMenu4.add(altaMovil);

        jMenuItem1.setText("Empleado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenu1.add(jMenu4);

        jMenu5.setText("Baja");

        jMenu9.setText("Empleado");
        jMenu5.add(jMenu9);

        jMenuItem8.setText("Afiliado");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem3.setText("Familia de Afiliados");
        jMenu5.add(jMenuItem3);

        bajaMovil.setText("Movil");
        bajaMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaMovilActionPerformed(evt);
            }
        });
        jMenu5.add(bajaMovil);

        jMenu1.add(jMenu5);

        Pago.setText("Pago");
        Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagoActionPerformed(evt);
            }
        });
        jMenu1.add(Pago);

        jMenuBar1.add(jMenu1);

        mItmAltaSolicitud.setText("Registro");
        mItmAltaSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmAltaSolicitudActionPerformed(evt);
            }
        });

        jMenu7.setText("jMenu7");
        mItmAltaSolicitud.add(jMenu7);

        jMenuItem9.setText("Solicitud");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mItmAltaSolicitud.add(jMenuItem9);

        jMenuBar1.add(mItmAltaSolicitud);

        jMenu3.setText("Lista");

        listaMoviles.setText("Moviles");
        listaMoviles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMovilesActionPerformed(evt);
            }
        });
        jMenu3.add(listaMoviles);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaMovilActionPerformed
        AltaMovil ventana = new AltaMovil(gestor);
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);              
        ventana.show();
    }//GEN-LAST:event_altaMovilActionPerformed

    private void PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagoActionPerformed
        EstablecerPago ventana = new EstablecerPago(gestor);
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);              
        ventana.show();
    }//GEN-LAST:event_PagoActionPerformed

    private void altaAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaAfiliadoActionPerformed
        AltaAfiliado ventana= new AltaAfiliado(gestor);
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);              
        ventana.show();
    }//GEN-LAST:event_altaAfiliadoActionPerformed

    private void bajaMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaMovilActionPerformed
        BajaMovil ventana= new BajaMovil(this,gestor);
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);              
        ventana.show();
    }//GEN-LAST:event_bajaMovilActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AltaEmpleado ventana= new AltaEmpleado(gestor);
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);              
        ventana.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        BajaAfiliado ventana= new BajaAfiliado(this,gestor);
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);              
        ventana.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void mItmAltaSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmAltaSolicitudActionPerformed
        
    }//GEN-LAST:event_mItmAltaSolicitudActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        AltaSolicitud ventana= new AltaSolicitud(this,gestor);
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);              
        ventana.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void listaMovilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMovilesActionPerformed
        ListaMoviles ventana= new ListaMoviles(gestor);
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ventana.show();
    }//GEN-LAST:event_listaMovilesActionPerformed

    private void altaFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaFamiliaActionPerformed
        AltaFamilia ventana= new AltaFamilia(this,gestor);
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ventana.show();
    }//GEN-LAST:event_altaFamiliaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Pago;
    private javax.swing.JMenuItem altaAfiliado;
    private javax.swing.JMenuItem altaFamilia;
    private javax.swing.JMenuItem altaMovil;
    private javax.swing.JMenuItem bajaMovil;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem listaMoviles;
    private javax.swing.JMenu mItmAltaSolicitud;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getJDesktopPane1() {
        return jDesktopPane1;
    }


}
