/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emergencias_medicas.ui;

import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import emergencias_medicas.Movil;
import emergencias_medicas.Gestor;
import javax.swing.JDesktopPane;

/**
 *
 * @author Carlos Mansilla
 */
public class UIPrincipal extends javax.swing.JFrame {
    
    private Gestor gestor;

    /**
     * Creates new form UI_Principal
     */
    public UIPrincipal(Gestor gestor) {
        this.gestor=gestor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mItmAltaAfiliado = new javax.swing.JMenuItem();
        mItmAltaMovil = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        mItmPago = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        jMenu1.setText("Administraccion");

        jMenu4.setText("Alta");

        jMenu8.setText("Empleado");

        jMenuItem4.setText("Administrativo");
        jMenu8.add(jMenuItem4);

        jMenuItem5.setText("Doctor");
        jMenu8.add(jMenuItem5);

        jMenuItem6.setText("Enfermero");
        jMenu8.add(jMenuItem6);

        jMenuItem7.setText("Chofer");
        jMenu8.add(jMenuItem7);

        jMenu4.add(jMenu8);

        mItmAltaAfiliado.setText("Afiliado");
        mItmAltaAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmAltaAfiliadoActionPerformed(evt);
            }
        });
        jMenu4.add(mItmAltaAfiliado);

        mItmAltaMovil.setText("Movil");
        mItmAltaMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmAltaMovilActionPerformed(evt);
            }
        });
        jMenu4.add(mItmAltaMovil);

        jMenu1.add(jMenu4);

        jMenu5.setText("Baja");

        jMenu9.setText("Empleado");
        jMenu5.add(jMenu9);

        jMenuItem8.setText("Afiliado");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Movil");
        jMenu5.add(jMenuItem9);

        jMenu1.add(jMenu5);

        mItmPago.setText("Pago");
        mItmPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItmPagoActionPerformed(evt);
            }
        });
        jMenu1.add(mItmPago);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registro");

        jMenu7.setText("jMenu7");
        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItmAltaMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmAltaMovilActionPerformed
        AltaMovil ventana = new AltaMovil(gestor);
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);              
        ventana.show();
    }//GEN-LAST:event_mItmAltaMovilActionPerformed

    private void mItmPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mItmPagoActionPerformed

    private void mItmAltaAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItmAltaAfiliadoActionPerformed
        AltaAfiliado ventana= new AltaAfiliado(gestor);
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);              
        ventana.show();
    }//GEN-LAST:event_mItmAltaAfiliadoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem mItmAltaAfiliado;
    private javax.swing.JMenuItem mItmAltaMovil;
    private javax.swing.JMenuItem mItmPago;
    // End of variables declaration//GEN-END:variables
}
